### PR TITLE
Patch eigenpy for better integration

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@conda-forge-admin, please rerender

**Comment by jcarpent** [comment]
@traversaro I think this new fix should help your former issue with eigenpy. Could you confirm?

**Comment by traversaro** [comment]
> @traversaro I think this new fix should help your former issue with eigenpy. Could you confirm?

Thanks! The patch is a bit big to inspect manually. Do you have any idea on how I could confirm? Otherwise we can merge and then I check if the CI is fixed.

**Comment by jcarpent** [comment]
I will provide a new release today as it also impacts ROS ;)

**Comment by traversaro** [comment]
FYI, after this PR now `find_package(pinocchio)` fails also on Linux/macOS, see:
~~~
-- eigenpy FOUND. eigenpy at /usr/share/miniconda/envs/test/lib/libeigenpy.so
CMake Error at /usr/share/miniconda/envs/test/lib/cmake/eigenpy/eigenpyConfig.cmake:136 (FINDPYTHON):
  Unknown CMake command "FINDPYTHON".
Call Stack (most recent call first):
  /usr/share/miniconda/envs/test/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/share/miniconda/envs/test/lib/cmake/pinocchio/pinocchioConfig.cmake:155 (find_dependency)
  cmake/iDynForDependencies.cmake:12 (find_package)
  CMakeLists.txt:128 (include)
~~~

**Pull request merged**
