### PR TITLE
Fix issue related to packaging

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@conda-forge-admin please rerender

**Comment by lesteve** [comment]
Can you explain a bit what you are trying to do? Did you only mean to change the build number or maybe this is WIP and you mean to add more changes?

**Comment by jcarpent** [comment]
@lesteve I was not making my PR against the correct branch sorry.
I also changed the patch to include some fixes in the generation of the PKG-CONFIG file which has been introduced by the PR https://github.com/stack-of-tasks/eigenpy/pull/97 on EigenPy

**Comment by jcarpent** [comment]
In the previous versions, the lib extension was exported, which should be avoided in the linkage standard. I remove then the extension when generation the export of eigenpy.pc

**Comment by jcarpent** [comment]
Seems good now. I'm going to merge this PR and then I will re-launch the Pinocchio builds.

**Pull request merged**
