### PR TITLE
Fix cross compilation

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@wolfv @xhochy I've trouble for making cross-compilation working properly on my setup for osx arm architecture.
When looking at the azure ci, it appears that for this specific build, the path to numpy is given by:
```
-- checking for numpy
--   NUMPY_INCLUDE_DIRS=$BUILD_PREFIX/venv/lib/python3.9/site-packages/numpy/core/include
--   NUMPY_VERSION=1.19.5
```

Do you know whether it could be rather pointing to: `$PREFIX/venv/lib/python3.9/site-packages/numpy/core/include`?
Thanks in advance for your help,

Best,

Justin

**Comment by jcarpent** [comment]
In fact, the question is rather why Numpy has been installed in `$BUILD_PREFIX/venv/lib/python3.9/site-packages/numpy/core/include`?

**Comment by xhochy** [comment]
> In fact, the question is rather why Numpy has been installed in `$BUILD_PREFIX/venv/lib/python3.9/site-packages/numpy/core/include`?

Because it is listed as a `build` dependency and that is OK. 

I think the correct fix would be to explicitly set `-DNUMPY_INCLUDE_DIRS=${SP_DIR}/numpy/core/include` in the cmake call.

**Comment by xhochy** [comment]
> Because it is listed as a `build` dependency and that is OK.

OK as in we need that for the `cross-python` magic to work.

**Comment by jcarpent** [comment]
> > In fact, the question is rather why Numpy has been installed in `$BUILD_PREFIX/venv/lib/python3.9/site-packages/numpy/core/include`?
> 
> Because it is listed as a `build` dependency and that is OK.
> 
> I think the correct fix would be to explicitly set `-DNUMPY_INCLUDE_DIRS=${SP_DIR}/numpy/core/include` in the cmake call.

I've tested that but it appears that the path does not exist on the build machine, while eigenpy needs it for compiling.

**Comment by jcarpent** [comment]
Should I perform a symbolic link?

**Comment by xhochy** [comment]
It's a bit spooky that `${SP_DIR}/numpy/core/include` doesn't exist as the same path exists in the build environment. Otherwise this looks fine.

**Comment by jcarpent** [comment]
> It's a bit spooky that `${SP_DIR}/numpy/core/include` doesn't exist as the same path exists in the build environment. Otherwise this looks fine.

@xhochy Seems to work finally. Thanks for your help.

**Pull request merged**
