### PR TITLE
pkg-config issue with eigenpy 1.5.6 on conda-forge

### PR DESCRIPTION
**Pull request by lesteve**
At the moment if you install `eigenpy` from conda-forge, `pkg-config` will not be able to find it. The reason seems that `eigenpy.pc` is in `$CONDA_PREFIX/lib64` whereas all the others `.pc` in the conda environment are in `$CONDA_PREFIX/lib`.

Delving a bit into the cmake files, it seems like this is because conda-forge uses a CentOS-based docker container and that the default for a non-Debian install is to use lib64 (full disclosure: no idea why the shared libraries end up in lib and not lib64 though).

A work-around for this would be to set CMAKE_INSTALL_LIBDIR=lib, any strong opinions about this @jcarpent? I'll try this in this PR too.

To reproduce:
```
conda create -n test-env -c conda-forge eigenpy pkg-config
conda activate test-env
pkg-config --modversion eigenpy
```
Output:
```
Package eigenpy was not found in the pkg-config search path.
Perhaps you should add the directory containing `eigenpy.pc'
to the PKG_CONFIG_PATH environment variable
No package 'eigenpy' found
```

### CODE REVIEW

**Comment by jcarpent** [comment]
On the CentOS system, all the *.pc files are installed in the lib64 folder?

**Comment by lesteve** [comment]
Inside a conda environment they always use lib and never use lib64 (irrespective the underlying OS). I did not find anything too explicit, but [this](https://github.com/conda/conda-build/issues/244) seems to agree with my understanding.

**Comment by lesteve** [comment]
The previous commit does reproduce the bug on the CI. I just pushed the `CMAKE_INSTALL_LIBDIR=lib` change to see whether that fixes it.

**Comment by lesteve** [comment]
OK merging this one.

**Comment by jcarpent** [comment]
@lesteve Can you try this line:
`from distutils import sysconfig; print(sysconfig.get_python_lib(prefix='', plat_specific=False))` on the problematic OS?

**Comment by lesteve** [comment]
```
❯ docker run -t condaforge/linux-anvil-comp7 bash -c 'python -c "from distutils import sysconfig; print(sysconfig.get_python_lib(prefix=\"\", plat_specific=False))"'
```

Output:
```
lib/python3.7/site-packages
```

**Comment by lesteve** [comment]
Are you saying you would rather have a fix in the cmake files, rather than in the conda-forge recipe?

**Comment by jcarpent** [comment]
This line comes from the cmake file in fact. I think the change you suggested is the correct way to force the installation inside the `lib` directory.

**Comment by jcarpent** [comment]
I approve this PR.

**Pull request merged**
